baseurl = "https://fbxhax.github.io/"
languageCode = "en-us"
title = "Fairbanks Hackathon"
theme = 'fbxhackathon'
canonifyurls = true

[params]
  name = "Fairbanks Hackathon"
  description = "Fairbanks Hackathon"
